import type { Metadata } from 'next';
import { Archivo_Black, Bebas_Neue, Nunito } from 'next/font/google';
import './globals.css';

const archivoBlack = Archivo_Black({
  weight: '400',
  variable: '--font-archivo-black',
  preload: true,
  subsets: ['latin'],
  display: 'swap',
});

const bebasNeue = Bebas_Neue({
  weight: '400',
  variable: '--font-bebas-neue',
  preload: true,
  subsets: ['latin'],
  display: 'swap',
});

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600'],
  variable: '--font-nunito',
  preload: true,
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Page Scroll Animation | Codegrid Rebuild',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${nunito.variable} ${archivoBlack.variable} flex h-full w-full flex-col items-center bg-[#0f0f0f] font-sans text-white`}
      >
        {children}
      </body>
    </html>
  );
}
