import type { Metadata } from 'next'
import { Archivo_Black, Bebas_Neue } from 'next/font/google'
import './globals.css'

const archivoBlack = Archivo_Black({ weight: '400', variable: '--font-archivo-black', subsets: ['latin'], preload: true })
const bebasNeue = Bebas_Neue({ weight: '400', variable: '--font-bebas-neue', subsets: ['latin'], preload: true })

export const metadata: Metadata = {
  title: 'Page Scroll Animation | Codegrid Rebuild',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${archivoBlack.className} ${bebasNeue.className}`}>{children}</body>
    </html>
  )
}
